name: Build with XC16 and Run Cppcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: XC16 Build and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all .c files recursively with xc16-gcc
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            ziadelbouriny/xc16:v2.10 \
            bash -eux -c '
              mkdir -p build

              # Collect include directories
              INCLUDE_DIRS=$(find modules -type d -name inc)
              INCLUDE_DIRS="$INCLUDE_DIRS config/ide/Bright_intern.X/mcc_generated_files config/ide/Bright_intern.X"

              INCLUDES=""
              for inc in $INCLUDE_DIRS; do
                INCLUDES="$INCLUDES -I$inc"
              done
              INCLUDES="$INCLUDES -I."

              # Find all .c files in modules and project
              SRC_FILES=$(find modules -type f -name "*.c")
              SRC_FILES="$SRC_FILES $(find config/ide/Bright_intern.X -type f -name '*.c')"

              for src in $SRC_FILES; do
                obj=build/$(basename "${src%.c}.o")
                echo "Compiling $src -> $obj"
                xc16-gcc $INCLUDES "$src" -mcpu=33EP256MC506 -c -o "$obj"
              done

              echo "Linking..."
              xc16-gcc -mcpu=33EP256MC506 -Wl,-Tp33EP256MC506.gld build/*.o -o build/project.elf
            '

      - name: Run cppcheck on all C files
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            ziadelbouriny/xc16:v2.10 \
            bash -eux -c '
              cppcheck --enable=all --inconclusive --quiet --suppress=missingInclude modules config
            '

      - name: Upload ELF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-elf
          path: build/project.elf





