name: Build with XC16 and Run Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: XC16 Build and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all .c files in project
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/ubuntu/project \
            -w /home/ubuntu/project \
            ziadelbouriny/xc16:v2.10 \
            bash -lc "\
              mkdir -p build && \
              for src in tools/*.c; do \
                obj=\"build/$(basename \"${src%.c}.o\")\"; \
                xc16-gcc \"\$src\" -mcpu=33EP256MC506 -c -o \"\$obj\"; \
              done && \
              xc16-gcc build/*.o -mcpu=33EP256MC506 -o build/project.elf || true"
      - name: Run cppcheck on all code
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/ubuntu/project \
            -w /home/ubuntu/project \
            ziadelbouriny/xc16:v2.10 \
            cppcheck --enable=all --inconclusive --std=c99 tools

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/project.elf


