name: Build with XC16 and Run Cppcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: XC16 Build and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all .c files recursively with xc16-gcc
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            ziadelbouriny/xc16:v2.10 \
            bash -eux -c '
              mkdir -p build

              # Collect all include directories with headers
              INCLUDE_DIRS=$(find mcc_generated_files -type f -name "*.h" -exec dirname {} \; | sort -u)

              INCLUDES=""
              for inc in $INCLUDE_DIRS; do
                INCLUDES="$INCLUDES -I$inc"
              done
              INCLUDES="$INCLUDES -I. -Imcc_generated_files"

              # Compile all C source files
              SRC_FILES=$(find . -type f -name "*.c")
              for src in $SRC_FILES; do
                obj="build/${src//\//_}.o"  # safe object filename
                echo "Compiling $src -> $obj"
                xc16-gcc $INCLUDES "$src" -mcpu=33EP256MC506 -c -o "$obj"
              done

              echo "Linking all object files..."
              # Link all compiled object files with required linker flags
              xc16-gcc build/*.o -mcpu=33EP256MC506 -Wl,--script=p33EP256MC506.gld -lpic30 -lm -o build/project.elf
            '

      - name: Run cppcheck on all C files
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            ziadelbouriny/xc16:v2.10 \
            bash -eux -c '
              cppcheck --enable=all --inconclusive --quiet --suppress=missingInclude .
            '

      - name: Upload ELF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-elf
          path: build/project.elf




